// Code generated by sqlc. DO NOT EDIT.

package tutorial

import (
	"database/sql"
)

type Article struct {
	ID           int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	Title        string
	Cid          int64
	Desc         sql.NullString
	Content      sql.NullString
	Img          sql.NullString
	CommentCount int64
	ReadCount    int64
}

type Category struct {
	ID   int64
	Name string
}
